# Generated by Django 4.2.7 on 2024-09-14 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('min_ph', models.FloatField()),
                ('max_ph', models.FloatField()),
            ],
        ),
    ]
